CarBox/CarBox/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarBox.Models;
using CarBox.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarBox.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        IDbRepositories<Car> repo;
        IDbRepositories<User> rep;
        public CarsController(IDbRepositories<Car> crepo, IDbRepositories<User> urep)
        {
            repo = crepo;
            rep = urep;
        }
        public IActionResult Index()
        {
            return View(repo.GetList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            SelectList users = new SelectList(rep.GetList(), "Id", "FirstName");
            ViewBag.Users = users;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Car car)
        {
            repo.Create(car);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                SelectList users = new SelectList(rep.GetList(), "Id", "FirstName");
                ViewBag.Users = users;
                Car car = repo.Get(id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(Car car)
        {
            repo.Update(car);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Car car = repo.Get(id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                repo.Delete(id);
                    return RedirectToAction("Index");
                
            }
            return NotFound();
        }
    }
}

CarBox/CarBox/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarBox.Models;
using CarBox.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarBox.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        IDbRepositories<User> repo;
        public UsersController(IDbRepositories<User> urepo)
        {
            repo = urepo;
        }
        public IActionResult Index()
        {
            var identity = User.Identity as ClaimsIdentity;
            Claim identityClaim = identity.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name);
            ViewBag.Role = repo.GetRole(identityClaim);
            return View(repo.GetList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                repo.Create(user);
                return RedirectToAction("Index");
            }
            else
                return Create();
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                User user = repo.Get(id);
                if (user != null)
                    return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                repo.Update(user);
                return RedirectToAction("Index");
            }
            else
                return Edit(user);
        }
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                User user = repo.Get(id);
                if (user != null)
                    return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                repo.Delete(id);
                    return RedirectToAction("Index");
                
            }
            return NotFound();
        }
    }
}

CarBox/CarBox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarBox</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Morris -->
    <link href="~/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

    <!-- Data Tables -->
    <link href="~/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="~/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="~/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
</head>

<body class="pace-done mini-navbar">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side">
            <div class="sidebar-collapse">
                <ul class="nav">
                    <li>
                        <a href=""><i class="fa fa-th-large"></i></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" style="margin-bottom: 0">
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Account" asp-route-id="">Account</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="wrapper wrapper-content">
                @RenderBody()
            </div>
            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Example Company &copy; 2014-2015
                </div>
            </div>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="~/js/jquery-2.1.1.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Flot -->
    <script src="~/js/plugins/flot/jquery.flot.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.spline.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.pie.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.symbol.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.time.js"></script>

    <!-- Peity -->
    <script src="~/js/plugins/peity/jquery.peity.min.js"></script>
    <script src="~/js/demo/peity-demo.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/js/inspinia.js"></script>
    <script src="~/js/plugins/pace/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="~/js/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Jvectormap -->
    <script src="~/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

    <!-- EayPIE -->
    <script src="~/js/plugins/easypiechart/jquery.easypiechart.js"></script>

    <!-- Sparkline -->
    <script src="~/js/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <script src="~/js/demo/sparkline-demo.js"></script>

    <!-- Data Tables -->
    <script src="js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="js/plugins/dataTables/dataTables.tableTools.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.chart').easyPieChart({
                barColor: '#f8ac59',
                //                scaleColor: false,
                scaleLength: 5,
                lineWidth: 4,
                size: 80
            });

            $('.chart2').easyPieChart({
                barColor: '#1c84c6',
                //                scaleColor: false,
                scaleLength: 5,
                lineWidth: 4,
                size: 80
            });

            var data2 = [
                [gd(2012, 1, 1), 7], [gd(2012, 1, 2), 6], [gd(2012, 1, 3), 4], [gd(2012, 1, 4), 8],
                [gd(2012, 1, 5), 9], [gd(2012, 1, 6), 7], [gd(2012, 1, 7), 5], [gd(2012, 1, 8), 4],
                [gd(2012, 1, 9), 7], [gd(2012, 1, 10), 8], [gd(2012, 1, 11), 9], [gd(2012, 1, 12), 6],
                [gd(2012, 1, 13), 4], [gd(2012, 1, 14), 5], [gd(2012, 1, 15), 11], [gd(2012, 1, 16), 8],
                [gd(2012, 1, 17), 8], [gd(2012, 1, 18), 11], [gd(2012, 1, 19), 11], [gd(2012, 1, 20), 6],
                [gd(2012, 1, 21), 6], [gd(2012, 1, 22), 8], [gd(2012, 1, 23), 11], [gd(2012, 1, 24), 13],
                [gd(2012, 1, 25), 7], [gd(2012, 1, 26), 9], [gd(2012, 1, 27), 9], [gd(2012, 1, 28), 8],
                [gd(2012, 1, 29), 5], [gd(2012, 1, 30), 8], [gd(2012, 1, 31), 25]
            ];

            var data3 = [
                [gd(2012, 1, 1), 800], [gd(2012, 1, 2), 500], [gd(2012, 1, 3), 600], [gd(2012, 1, 4), 700],
                [gd(2012, 1, 5), 500], [gd(2012, 1, 6), 456], [gd(2012, 1, 7), 800], [gd(2012, 1, 8), 589],
                [gd(2012, 1, 9), 467], [gd(2012, 1, 10), 876], [gd(2012, 1, 11), 689], [gd(2012, 1, 12), 700],
                [gd(2012, 1, 13), 500], [gd(2012, 1, 14), 600], [gd(2012, 1, 15), 700], [gd(2012, 1, 16), 786],
                [gd(2012, 1, 17), 345], [gd(2012, 1, 18), 888], [gd(2012, 1, 19), 888], [gd(2012, 1, 20), 888],
                [gd(2012, 1, 21), 987], [gd(2012, 1, 22), 444], [gd(2012, 1, 23), 999], [gd(2012, 1, 24), 567],
                [gd(2012, 1, 25), 786], [gd(2012, 1, 26), 666], [gd(2012, 1, 27), 888], [gd(2012, 1, 28), 900],
                [gd(2012, 1, 29), 178], [gd(2012, 1, 30), 555], [gd(2012, 1, 31), 993]
            ];


            var dataset = [
                {
                    label: "Number of orders",
                    data: data3,
                    color: "#1ab394",
                    bars: {
                        show: true,
                        align: "center",
                        barWidth: 24 * 60 * 60 * 600,
                        lineWidth: 0
                    }

                }, {
                    label: "Payments",
                    data: data2,
                    yaxis: 2,
                    color: "#464f88",
                    lines: {
                        lineWidth: 1,
                        show: true,
                        fill: true,
                        fillColor: {
                            colors: [{
                                opacity: 0.2
                            }, {
                                opacity: 0.2
                            }]
                        }
                    },
                    splines: {
                        show: false,
                        tension: 0.6,
                        lineWidth: 1,
                        fill: 0.1
                    },
                }
            ];


            var options = {
                xaxis: {
                    mode: "time",
                    tickSize: [3, "day"],
                    tickLength: 0,
                    axisLabel: "Date",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: 'Arial',
                    axisLabelPadding: 10,
                    color: "#d5d5d5"
                },
                yaxes: [{
                    position: "left",
                    max: 1070,
                    color: "#d5d5d5",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: 'Arial',
                    axisLabelPadding: 3
                }, {
                    position: "right",
                    clolor: "#d5d5d5",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: ' Arial',
                    axisLabelPadding: 67
                }
                ],
                legend: {
                    noColumns: 1,
                    labelBoxBorderColor: "#000000",
                    position: "nw"
                },
                grid: {
                    hoverable: false,
                    borderWidth: 0
                }
            };

            function gd(year, month, day) {
                return new Date(year, month - 1, day).getTime();
            }

            var previousPoint = null, previousLabel = null;

            //$.plot($("#flot-dashboard-chart"), dataset, options);

            var mapData = {
                "US": 298,
                "SA": 200,
                "DE": 220,
                "FR": 540,
                "CN": 120,
                "AU": 760,
                "BR": 550,
                "IN": 200,
                "GB": 120,
            };

            $('#world-map').vectorMap({
                map: 'world_mill_en',
                backgroundColor: "transparent",
                regionStyle: {
                    initial: {
                        fill: '#e4e4e4',
                        "fill-opacity": 0.9,
                        stroke: 'none',
                        "stroke-width": 0,
                        "stroke-opacity": 0
                    }
                },

                series: {
                    regions: [{
                        values: mapData,
                        scale: ["#1ab394", "#22d6b1"],
                        normalizeFunction: 'polynomial'
                    }]
                },
            });
        });

    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>